### ISSUE TITLE
End credits text issue and crash

### ISSUE THREAD

**Issue by vaguerant** [Baoulettes/Shipwright-linux#1]
Originally reported as GaryOderNichts/Shipwright#8, these two issues have been [confirmed by pancake on the Discord](https://discord.com/channels/808039310850130000/955958338384982126/965505899135397918) to occur on this fork.

I'll quote the relevant parts from the original issue from Gary's fork.

> 1) Some screens during the credits briefly display the word "Deleted" in the top left of the screen, in the normal text/credits font. This occurs twice. Not terribly alarming, but certainly odd.

> ![Deleted #1](https://user-images.githubusercontent.com/5259025/163711657-dd3b92a1-9286-48eb-aea0-77a72160091f.jpg)

> ![Deleted #2](https://user-images.githubusercontent.com/5259025/163711662-69044d9e-4324-460e-bb16-f110e985b579.jpg)

> 3) The game locks up immediately after the sequence at [8:55 in this video](https://youtu.be/Pv0_-5DCsi0?t=535). This issue superficially looks extremely similar to GaryOderNichts/Shipwright#6--it fades to black right at the transition from the end of the credits to the post-credits scene and locks up forever there. Obviously, the game is already beaten at this point, so it's not possible to lose progress or anything like that, but it's not ideal.

Here is pancake's error log as reported in the Discord discussion linked above:

```
soh.elf: libultraship/Lib/Fast3D/gfx_pc.cpp:1725: void gfx_dp_load_tile(uint8_t, uint32_t, uint32_t, uint32_t, uint32_t): Assertion `tile == 7' failed.
Aborted (core dumped)
```

The original issue filing on Gary's repo included another issue, where the skybox scales incorrectly, but this one appears to be Wii U-exclusive.

**EDIT:** For testing purposes, the fastest way I know to get to the end credits is to enable debug mode and use the Map Select to jump straight to Map 89. This will play the castle collapse cutscene then allow the player to go directly to the final battle with Beast Ganon.

**Comment by Baoulettes** [comment]
Deleted texts fixed with this PR:
https://github.com/Baoulettes/Shipwright-linux/pull/2
Till I think and do a better method there is this approach :)

**Comment by Baoulettes** [comment]
Properly fixed both issues with these : 
https://github.com/Baoulettes/Shipwright-linux/commit/92f1dd5c3b41630ac0cf91cb71e17e4fbcff0f24
https://github.com/Baoulettes/Shipwright-linux/commit/472f256747ab7fa660505424ba71d793e7d26a79
